// Generates db/seed.sql from the current hardcoded content sources:
//   - src/data/shopItems.ts      → pianos + images
//   - src/data/concerts.ts       → concerts + posters + concert gallery
//   - src/data/workshopServices.ts → workshop_categories + services + images
//   - messages/{en,he}.json      → about_sections + founders
//
// Images are seeded with their existing local /public paths in `url`
// (storage_key stays NULL); Phase 4 migrates the files to R2 and fills the key.
//
// Run with:  node scripts/generate-seed.ts   (Node 24 strips TS types natively)

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { shopItems } from '../src/data/shopItems.ts';
import { concerts, concertGallery } from '../src/data/concerts.ts';
import { workshopCategories } from '../src/data/workshopServices.ts';
import en from '../messages/en.json' with { type: 'json' };
import he from '../messages/he.json' with { type: 'json' };

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../db/seed.sql');

// ── SQL literal helpers ─────────────────────────────────────────────────────
const s = (v: string | null | undefined): string =>
  v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const n = (v: number | null | undefined): string => (v == null ? 'NULL' : String(v));
const b = (v: boolean | undefined): string => (v ? '1' : '0');

// Founder id → photo, and about-section key → photo (from the About page).
const FOUNDER_IMG: Record<string, string> = {
  gadi: '/images/About/Gadi.jpg',
  nethanel: '/images/About/Fastman.jpg',
  noam: '/images/About/Noam.jpg',
};
const ABOUT_IMG: Record<string, string> = {
  studio: '/images/About/about-trio.jpg',
  who: '/images/About/who-we-are.jpeg',
};

const lines: string[] = [];
lines.push('-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand.');
// No explicit BEGIN/COMMIT: remote D1 wraps file execution in its own atomic
// transaction and rejects manual transaction statements.
lines.push('');
// Idempotent: clear everything (children first) before re-inserting.
for (const t of [
  'registrations',
  'images',
  'workshop_services',
  'workshop_categories',
  'concerts',
  'pianos',
  'founders',
  'about_sections',
]) {
  lines.push(`DELETE FROM ${t};`);
}
lines.push('');

let imageId = 0;
const img = (
  entityType: string,
  entityId: string,
  url: string,
  sort: number,
  alt?: { en?: string; he?: string },
) => {
  imageId += 1;
  lines.push(
    `INSERT INTO images (entity_type, entity_id, url, sort_order, alt_en, alt_he) VALUES ` +
      `(${s(entityType)}, ${s(entityId)}, ${s(url)}, ${sort}, ${s(alt?.en)}, ${s(alt?.he)});`,
  );
};

// ── Pianos ──────────────────────────────────────────────────────────────────
lines.push('-- Pianos');
shopItems.forEach((p, i) => {
  const price = p.price === 'contact' ? null : (p.price as number);
  lines.push(
    `INSERT INTO pianos (id, brand, model, type, serial, region, size, price_ils, ` +
      `color_hex, color_name_en, color_name_he, dim_width, dim_height, dim_depth, ` +
      `description_en, description_he, details_en, details_he, wip, sort_order) VALUES (` +
      `${s(p.id)}, ${s(p.brand)}, ${s(p.model)}, ${s(p.type)}, ${s(p.serial)}, ${s(p.region)}, ` +
      `${s(p.size)}, ${n(price)}, ${s(p.color.hex)}, ${s(p.color.name.en)}, ${s(p.color.name.he)}, ` +
      `${n(p.dimensions.width)}, ${n(p.dimensions.height)}, ${n(p.dimensions.depth)}, ` +
      `${s(p.description?.en)}, ${s(p.description?.he)}, ${s(p.details?.en)}, ${s(p.details?.he)}, ` +
      `${b(p.wip)}, ${i});`,
  );
  const imgsList = p.images && p.images.length ? p.images : [p.image];
  imgsList.forEach((url, j) => img('piano', p.id, url, j));
});
lines.push('');

// ── Concerts + posters + gallery ─────────────────────────────────────────────
lines.push('-- Concerts');
concerts.forEach((c, i) => {
  lines.push(
    `INSERT INTO concerts (id, name_en, name_he, date, time, venue_en, venue_he, ` +
      `price_ils, description_en, description_he, sort_order) VALUES (` +
      `${s(c.id)}, ${s(c.name.en)}, ${s(c.name.he)}, ${s(c.date)}, ${s(c.time)}, ` +
      `${s(c.venue.en)}, ${s(c.venue.he)}, ${n(c.price)}, ` +
      `${s(c.description?.en)}, ${s(c.description?.he)}, ${i});`,
  );
  img('concert', c.id, c.poster, 0, { en: c.name.en, he: c.name.he });
});
lines.push('-- Concert gallery (site-wide)');
concertGallery.forEach((url, i) => img('gallery', 'concerts', url, i));
lines.push('');

// ── Workshop categories + services ────────────────────────────────────────────
lines.push('-- Workshop categories + services');
workshopCategories.forEach((cat, i) => {
  lines.push(
    `INSERT INTO workshop_categories (id, name_en, name_he, description_en, description_he, ` +
      `sort_order) VALUES (${s(cat.id)}, ${s(cat.name.en)}, ${s(cat.name.he)}, ` +
      `${s(cat.description.en)}, ${s(cat.description.he)}, ${i});`,
  );
  const imgsList = cat.images && cat.images.length ? cat.images : [cat.image];
  imgsList.forEach((url, j) => img('workshop_category', cat.id, url, j));
  cat.services.forEach((svc, j) => {
    lines.push(
      `INSERT INTO workshop_services (id, category_id, name_en, name_he, description_en, ` +
        `description_he, sort_order) VALUES (${s(svc.id)}, ${s(cat.id)}, ${s(svc.name.en)}, ` +
        `${s(svc.name.he)}, ${s(svc.description.en)}, ${s(svc.description.he)}, ${j});`,
    );
  });
});
lines.push('');

// ── About sections ────────────────────────────────────────────────────────────
lines.push('-- About sections');
const aboutSections: { key: string; titleEn: string; titleHe: string; bodyEn: string[]; bodyHe: string[] }[] = [
  {
    key: 'studio',
    titleEn: en.about.about_trio_title,
    titleHe: he.about.about_trio_title,
    bodyEn: en.about.about_trio_body,
    bodyHe: he.about.about_trio_body,
  },
  {
    key: 'who',
    titleEn: en.about.who_title,
    titleHe: he.about.who_title,
    bodyEn: en.about.who_body,
    bodyHe: he.about.who_body,
  },
];
aboutSections.forEach((sec, i) => {
  lines.push(
    `INSERT INTO about_sections (key, title_en, title_he, body_en, body_he, sort_order) VALUES (` +
      `${s(sec.key)}, ${s(sec.titleEn)}, ${s(sec.titleHe)}, ` +
      `${s(JSON.stringify(sec.bodyEn))}, ${s(JSON.stringify(sec.bodyHe))}, ${i});`,
  );
  img('about_section', sec.key, ABOUT_IMG[sec.key], 0);
});
lines.push('');

// ── Founders ────────────────────────────────────────────────────────────────
lines.push('-- Founders');
const founderOrder = ['gadi', 'nethanel', 'noam'] as const;
founderOrder.forEach((id, i) => {
  const fe = (en.about.founders as Record<string, { name: string; bio: string }>)[id];
  const fh = (he.about.founders as Record<string, { name: string; bio: string }>)[id];
  lines.push(
    `INSERT INTO founders (id, name_en, name_he, bio_en, bio_he, sort_order) VALUES (` +
      `${s(id)}, ${s(fe.name)}, ${s(fh.name)}, ${s(fe.bio)}, ${s(fh.bio)}, ${i});`,
  );
  img('founder', id, FOUNDER_IMG[id], 0, { en: fe.name, he: fh.name });
});
lines.push('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n', 'utf8');
console.log(`Wrote ${OUT} (${lines.length} statements, ${imageId} images).`);
